# Generated by Django 4.1.1 on 2022-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
