# Generated by Django 4.1.1 on 2022-09-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_movie_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="id",
        ),
        migrations.AddField(
            model_name="genre",
            name="_id",
            field=models.BigAutoField(
                default=10000000000, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
