# Generated by Django 4.1.1 on 2022-09-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_remove_genre_id_genre__id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="id",
        ),
        migrations.AddField(
            model_name="movie",
            name="_id",
            field=models.BigAutoField(
                default=100000000, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
