# Generated by Django 4.1.1 on 2022-09-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_movieposter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieposter",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="movie.movie",
            ),
        ),
    ]
