# Generated by Django 4.1.1 on 2022-09-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_alter_movieposter_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="dailyRentalRate",
            new_name="imdbRating",
        ),
    ]
