# Generated by Django 4.1.1 on 2022-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_remove_movie_numberinstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
