# Generated by Django 4.1.1 on 2022-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_movie_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="releaseDate",
            field=models.DateField(null=True),
        ),
    ]
