# Generated by Django 4.1.1 on 2022-10-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_promotions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotions",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
    ]
