# Generated by Django 4.1.1 on 2022-10-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_alter_promotions_movie"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Promotions",
            new_name="Promotion",
        ),
    ]
