# Generated by Django 4.1.1 on 2022-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_delete_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
