# Generated by Django 4.1.1 on 2022-10-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0017_alter_customer_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="subscriptionStatus",
        ),
        migrations.AlterField(
            model_name="customer",
            name="subscriptionType",
            field=models.CharField(
                choices=[("SL", "silver"), ("GD", "gold"), ("BR", "bronze")],
                default="IR",
                max_length=2,
            ),
        ),
    ]
