# Generated by Django 4.1.1 on 2022-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0018_remove_customer_subscriptionstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="subscriptionType",
            field=models.CharField(
                choices=[
                    ("SL", "silver"),
                    ("GD", "gold"),
                    ("BR", "bronze"),
                    ("IR", "iron"),
                ],
                default="IR",
                max_length=2,
            ),
        ),
    ]
