# Generated by Django 4.1.1 on 2022-10-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0019_alter_customer_subscriptiontype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="watchList",
        ),
    ]
