# Generated by Django 4.1.1 on 2022-10-05 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movie", "0021_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="WatchList",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="user",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="watchList",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
