# Generated by Django 4.1.1 on 2022-10-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0022_remove_watchlist_watchlist_remove_watchlist_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="watchList",
            new_name="movie",
        ),
    ]
