# Generated by Django 4.1.1 on 2022-10-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0023_rename_watchlist_watchlist_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="user",
        ),
    ]
