# Generated by Django 4.1.1 on 2022-10-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0024_remove_watchlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.customer",
            ),
            preserve_default=False,
        ),
    ]
