# Generated by Django 4.1.1 on 2022-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0027_remove_watchlist_customer_watchlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="subscriptionType",
            field=models.CharField(
                choices=[
                    ("SL", "silver"),
                    ("GD", "gold"),
                    ("BR", "bronze"),
                    ("FR", "free"),
                ],
                default="FR",
                max_length=2,
            ),
        ),
    ]
