# Generated by Django 4.1.1 on 2022-10-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0028_alter_customer_subscriptiontype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=255)),
                ("monthly_price", models.PositiveBigIntegerField()),
                ("video_quality", models.CharField(max_length=255)),
                ("resolution", models.CharField(max_length=255)),
                (
                    "devices",
                    models.CharField(
                        choices=[
                            ("MB", "mobile"),
                            ("TB", "tablet"),
                            ("CM", "computer"),
                            ("TV", "tv"),
                        ],
                        default="MB",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="subscriptionTypes",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.subcriptiontype",
            ),
            preserve_default=False,
        ),
    ]
