# Generated by Django 4.1.1 on 2022-10-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0029_subcriptiontype_customer_subscriptiontypes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
