# Generated by Django 4.1.1 on 2022-11-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0032_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_link",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
    ]
