# Generated by Django 4.1.1 on 2022-11-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0035_alter_videolink_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolink",
            name="link",
            field=models.URLField(),
        ),
    ]
