# Generated by Django 4.1.1 on 2022-11-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0036_alter_videolink_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videolink",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
    ]
