# Generated by Django 4.1.3 on 2022-11-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0038_alter_videolink_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="movie",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
            preserve_default=False,
        ),
    ]
