# Generated by Django 4.1.5 on 2023-01-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0042_alter_customer_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieposter",
            name="image",
            field=models.ImageField(upload_to="movieposter"),
        ),
    ]
