# Generated by Django 4.1.5 on 2023-01-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0043_alter_movieposter_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieposter",
            name="image",
            field=models.ImageField(upload_to="movieposters"),
        ),
    ]
